apiVersion: v1
kind: Pod
metadata:
  name: hello-kube-testing
  namespace: testing # namespace name
spec:
  containers:
    - image: 020896/hello-kube
      name: hello-kube
      ports:
        - containerPort: 3000
          protocol: TCP
