apiVersion: v1
kind: Pod
metadata:
  name: hello-kube-ios
  labels:
    app: ui
spec:
  containers:
    - image: 020896/hello-kube
      name: hello-kube
      ports:
        - containerPort: 3000
          protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: hello-kube-pc
  labels:
    app: ui
spec:
  containers:
    - image: 020896/hello-kube
      name: hello-kube
      ports:
        - containerPort: 3000
          protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: hello-kube-os
  labels:
    app: system
spec:
  containers:
    - image: 020896/hello-kube
      name: hello-kube
      ports:
        - containerPort: 3000
          protocol: TCP
