apiVersion: v1
kind: Secret
metadata:
  name: todo
type: Opaque
stringData:
  MYSQL_HOST: db
  MYSQL_PORT: "80"
  MYSQL_USER: myuser
  MYSQL_PASSWORD: myuserpass
  MYSQL_DATABASE: todo_app
  DATABASE_URL: mysql://myuser:myuserpass@db:80/todo_app
  MYSQL_ROOT_PASSWORD: rootpass

  # Note: Cách bên dưới chạy trong Docker nhưng không chạy trên k8s
  # DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
